CREATE DATABASE SAGE_MOCK;
GO
USE SAGE_MOCK;
GO

-- Table des utilisateurs (GESAUS)
CREATE TABLE AUTILIS (
    USR_0 VARCHAR(5) PRIMARY KEY,
    INTUSR_0 VARCHAR(100) NOT NULL,
    ENAFLG_0 INT NOT NULL DEFAULT 1,
    CODMET_0 VARCHAR(20) NOT NULL,
    ADDEML_0 VARCHAR(150) NULL
);

-- Table des traductions (ATEXTRA)
CREATE TABLE ATEXTRA (
    CODFIC_0 VARCHAR(50) NOT NULL,
    ZONE_0 VARCHAR(50) NOT NULL,
    IDENT1_0 VARCHAR(50) NOT NULL,
    LANGUE_0 VARCHAR(3) NOT NULL,
    TEXTE_0 VARCHAR(255) NOT NULL,
    PRIMARY KEY (CODFIC_0, ZONE_0, IDENT1_0, LANGUE_0)
);
GO

-- Jeu de données de test ERP
INSERT INTO AUTILIS (USR_0, INTUSR_0, ENAFLG_0, CODMET_0) VALUES
('54321', 'Amira Ben Ali', 1, 'PROD_GAZ'),
('12345', 'Ahmed Ben Salah', 1, 'QUAL'),
('99999', 'Karim Trabelsi', 1, 'MAG');

INSERT INTO ATEXTRA (CODFIC_0, ZONE_0, IDENT1_0, LANGUE_0, TEXTE_0) VALUES
('APROFMET', 'INTPRF', 'PROD_GAZ', 'FRA', 'Operateur Sopal Gaz'),
('APROFMET', 'INTPRF', 'QUAL', 'FRA', 'Administrateur Qualite'),
('APROFMET', 'INTPRF', 'MAG', 'FRA', 'Magasinier PF');
GO

