services:
  sopaltrace.api:
    image: ${DOCKER_REGISTRY-}sopaltraceapi
    build:
      context: .
      dockerfile: SopalTrace.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sopal_Password123! 
    ports:
      - "1433:1433"
    volumes:
      - sopal_db_data:/var/opt/mssql
volumes:
  sopal_db_data: